name: "Chromatic Deployment"

on:
  push:
    paths:
      - "packages/ui/**"

jobs:
  Chromatic-CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Monorepo install
        uses: ./.github/actions/yarn

      - name: Build Storybook
        run: yarn run build-storybook
        with:
          workingDir: packages/ui

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: packages/ui
          storybookBuildDir: storybook-static
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
